name: Deploy Backend to Railway

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.modified, 'backend/')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Link to Railway Project
        run: railway link
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up --service backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
