name: Deploy Frontend to Vercel

on: 
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

permissions:
  contents: read
  deployments: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Debug Info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workspace: ${{ github.workspace }}"
          echo "Modified files:"
          git diff --name-only HEAD^ HEAD
          echo "Current directory structure:"
          ls -la
          echo "Frontend directory structure:"
          ls -la frontend || echo "Frontend directory not found"
          echo "Git remote info:"
          git remote -v

      - name: Verify Secrets
        run: |
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "✓ VERCEL_TOKEN is set"
          else
            echo "✗ VERCEL_TOKEN is missing"
            exit 1
          fi
          if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "✓ VERCEL_ORG_ID is set"
          else
            echo "✗ VERCEL_ORG_ID is missing"
            exit 1
          fi
          if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "✓ VERCEL_PROJECT_ID is set"
          else
            echo "✗ VERCEL_PROJECT_ID is missing"
            exit 1
          fi

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          if [ ! -f "package.json" ]; then
            echo "Error: package.json not found in $(pwd)"
            exit 1
          fi
          echo "Installing dependencies from package.json"
          npm ci

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
          github-token: ${{ secrets.GITHUB_TOKEN }}
