name: Deploy Frontend to Vercel

on: 
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

permissions:
  contents: read
  deployments: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Debug Info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workspace: ${{ github.workspace }}"
          echo "Modified files:"
          git diff --name-only HEAD^ HEAD
          echo "Current directory structure:"
          ls -la
          echo "Frontend directory structure:"
          ls -la frontend || echo "Frontend directory not found"
          echo "Git remote info:"
          git remote -v
          echo "Git user info:"
          git config --get user.name || echo "No user.name set"
          git config --get user.email || echo "No user.email set"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          if [ ! -f "package.json" ]; then
            echo "Error: package.json not found"
            exit 1
          fi
          npm ci

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias-domains: |
            zacktransfer.com
            www.zacktransfer.com
