name: Deploy Frontend to Vercel

on: 
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

permissions:
  contents: read
  deployments: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Debug Info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workspace: ${{ github.workspace }}"
          echo "Modified files:"
          git diff --name-only HEAD^ HEAD
          echo "Current directory structure:"
          ls -la
          echo "Frontend directory structure:"
          ls -la frontend || echo "Frontend directory not found"

      - name: Verify Secrets
        run: |
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "✓ VERCEL_TOKEN is set"
          else
            echo "✗ VERCEL_TOKEN is missing"
            exit 1
          fi
          if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "✓ VERCEL_ORG_ID is set"
          else
            echo "✗ VERCEL_ORG_ID is missing"
            exit 1
          fi
          if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "✓ VERCEL_PROJECT_ID is set"
          else
            echo "✗ VERCEL_PROJECT_ID is missing"
            exit 1
          fi

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          if [ ! -f "package.json" ]; then
            echo "Error: package.json not found in $(pwd)"
            exit 1
          fi
          echo "Installing dependencies from package.json"
          npm ci
          echo "Installing Vercel CLI"
          npm install -g vercel

      - name: Deploy to Vercel
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "Attempting to deploy to Vercel..."
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
          echo "Linking project..."
          vercel link --token ${{ secrets.VERCEL_TOKEN }} --yes || echo "Link step failed but continuing..."
          
          echo "Pulling Vercel environment..."
          vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }} || echo "Pull step failed but continuing..."
          
          echo "Building project..."
          vercel build --prod --token ${{ secrets.VERCEL_TOKEN }} || echo "Build step failed but continuing..."
          
          echo "Deploying to Vercel..."
          VERCEL_DEBUG=1 vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
