name: Deploy Frontend to Vercel

on: 
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workspace: ${{ github.workspace }}"
          echo "Modified files:"
          git diff --name-only HEAD^ HEAD
          echo "Directory contents:"
          ls -la
          echo "Frontend directory contents:"
          ls -la frontend || echo "Frontend directory not found"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          echo "Installing project dependencies..."
          npm ci
          echo "Installing Vercel CLI..."
          npm install --global vercel@latest

      - name: Deploy to Vercel
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "Linking project..."
          vercel link --token ${{ secrets.VERCEL_TOKEN }} --yes
          
          echo "Deploying to Vercel..."
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}
